# Generated by Django 5.0.7 on 2024-07-24 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_category', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=100)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_expiration_date', models.DateTimeField()),
                ('task_priority', models.IntegerField(default=0)),
                ('task_status', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
